# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/attica': '@latest-kf6'
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kglobalaccel': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'frameworks/kpackage': '@latest-kf6'
    'frameworks/kservice': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'plasma/libksysguard': '@same'
RuntimeDependencies:
- 'on': ['@all']
  'require':
    'frameworks/kiconthemes': '@latest-kf6' # IconDialog
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
