# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/attica': '@latest'
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kconfig': '@latest'
    'frameworks/kcoreaddons': '@latest'
    'frameworks/kdbusaddons': '@latest'
    'frameworks/kdeclarative': '@latest'
    'frameworks/kglobalaccel': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kio': '@latest'
    'frameworks/kitemmodels': '@latest'
    'frameworks/knewstuff': '@latest'
    'frameworks/kpackage': '@latest'
    'frameworks/kservice': '@latest'
    'frameworks/kwindowsystem': '@latest'
    'plasma/libksysguard': '@same'
Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD']
